### ISSUE TITLE
Installation error due to scipy dependency

### ISSUE THREAD

**Issue by jjmccollum** [rbturnbull/dcodex#18] opened 2022-07-19 01:49 UTC
I've setup a D-Codex site using `dcodex-cookiecutter`, and I've successfully created a new project in a `dcodex_ephesians_ubs` directory.

I installed Python 3.9 in order to meet the `dcodex` package requirements and setup a virtual environment to use it for my project via

```
poetry env use <path>\<to>\Python39\python.exe
```

But when I try to install the project dependencies via

```
poetry install
```

I get the following error:

```
Because dcodex ephesians ubs depends on scipy (^1.8.0.dev0) which doesn't exist, version solving failed.
```

Is there something I'm doing wrong here? I already had the latest version of `scipy` (1.8.0) installed via `pip`, so I'm not sure why the dependency can't be found. I'm running this on Windows 10, so I specified `windows: y` in the `dcodex-cookiecutter` setup.

**Comment by rbturnbull** [comment] 2022-07-19 02:14
this might be the first install of dcodex on windows - great work! The scipy thing was an issue a few months ago getting it to work on an Apple M1 chip. The latest version of scipy should be good now and we won't need to use the 'dev' one. One of the dcodex plugins probably still pins 1.8.0.dev0 for scipy. I'll have a look.

**Comment by jjmccollum** [comment] 2022-07-19 02:19
Nice! It looks like if I simplify the line 

```
scipy = {version = "^1.8.0.dev0", source = "scipy-wheels-nightly"}
```

in `pyproject.toml` to

```
scipy = "^1.8.0.dev0"
```

then the installation proceeds beyond this point. Unfortunately, it stops because it can't build `python-Levenshtein`, since I don't (yet) have Microsoft C++ Build Tools installed on my system. I'll need to get someone with admin privileges to do this installation on my office machine, so it may be a while before I can revisit this. But that's a separate issue, so if the above change works fine on your end, then you are welcome to close this issue.

**Comment by rbturnbull** [comment] 2022-07-19 03:35
I think the problem is in django-cookiecutter. I'll fix it there and close this issue. Regarding python-Levenshtein, that is an old dependency. dcodex is now using my 'gotoh' package now for that. I'll see if I can get rid of it as a dependency

**Closed as completed** 2022-07-19 03:38 UTC

**Comment by rbturnbull** [comment] 2022-07-19 03:41
I've also added an issue (#19 ) to add in CI for dcodex-cookiecutter so that it catches problems like this.

**Comment by jjmccollum** [comment] 2022-07-19 04:08
Unfortunately, it looks like `gotoh` also requires Microsoft C++ Build Tools, so I'll need to wait till I get Visual Studio installed before I can proceed. But thanks for pushing the latest changes!

**Comment by rbturnbull** [comment] 2022-07-19 08:10
Thanks @jjmccollum - can you please make a note of things you have to do to install the dependencies on Windows and we can add instructions to this section of the docs: https://www.dcodex.net/dependencies.html#windows ?
If you want, you can directly add instructions in the docs as you go.

**Comment by jjmccollum** [comment] 2022-07-20 05:12
Thanks, @rbturnbull! I've added documentation for the Windows installation process to the project readme in this repo. If that takes up too much space on the project page, I'm fine with having it moved to the docs you linked to (although I may need you to edit the docs or remind me how I can edit them).

**Comment by jjmccollum** [comment] 2022-07-20 05:31
Nevermind, I just found the `dependencies.rst` file in the repo. I'll add the documentation to that now!
